### ISSUE TITLE
Release on F-Droid

### ISSUE THREAD

**Issue by locness3** [26F-Studio/Techmino#1059]
### What feature do you want to suggest to the game?

Please release this game on [F-Droid](https://f-droid.org/) for Android, it would make it more convenient to install the game and could bring it some visibility.

The process of releasing on F-Droid is somewhat unusual so you should read the [official documentation](https://f-droid.org/docs/).

**Comment by SweetSea-ButImNotSweet** [comment]
@ImpleLee can you consider? I don't think Z is able to do it although he wants...

**Comment by ImpleLee** [comment]
There are many platforms we can release on but we choose not to do that, such as steam, taptap, ichi.io, Google Store... That's not because we don't want visibility, but because we want to avoid TTC's DMCA, and most importantly, we don't want to get DMCA directly on GitHub, making our game no longer available for most users. We used to release on App Store because that's the only legal way to enable iOS users to play. Since F-Droid is not necessary to play on Android, I prefer not to make it available there.

**Comment by SweetSea-ButImNotSweet** [comment]
So... based on what you said, can we close this as not planned?

**Comment by ImpleLee** [comment]
> So... based on what you said, can we close this as not planned?

Ultimately I think it depends on @MrZ626 ...
