### ISSUE TITLE
disabling theme on android prevents the game from loading

### ISSUE THREAD

**Issue by GitEin11** [26F-Studio/Techmino#1174]
![Screenshot_2024-11-03-15-21-51-107_org f26_studio Techmino](https://github.com/user-attachments/assets/989ff362-1e42-41fe-a47a-18a907b57a53)

device: Redmi 13 note pro 5g

steps:
1. load the game
2. uncheck theme
3. reload the game
4. hang up until "loading other assets"

will only work again if I reset the app data, this resets the settings so I'm unable to disable theme.

**Comment by shoucandanghehe** [comment]
Hi, this is a known bug and should have been fixed by #1168.

One fix for the current version is: set your device's date to before October 31, re-enable the theme and adjust back to the correct time.

**Comment by SweetSea-ButImNotSweet** [comment]
Hi, I'm sorry for causing you this trouble and you have to reset your app
It waa my mistake, and the code of "Disable theme" was written by me. I made a bad logic that causes an infinity recursive loop

You can do scdhh's suggestion. But since you did a app data reset, you lost *literally* ***everything***, including your personal best and your replays. I'm, again, sorry for that.

**Comment by MrZ626** [comment]
fixed

**Comment by SweetSea-ButImNotSweet** [comment]
> the bug is back
Yeah, because it is only fixed in latest snapshot, and it has been a year since the last release

Very sorry
