### ISSUE TITLE
Mahjong: "International" style tiles

### ISSUE THREAD

**Issue by user670** [26F-Studio/Techmino#625]
### What feature do you want to suggest to the game?

International-style tiles to aid international players' gameplay (especially those that don't read chinese characters):

Features of international-style tiles include:

- all numbered tiles have the number written in the corner of the tile. ~~For Techmino, considering dots and bamboos are literally just numbers, it's only required that the numbers present on the character tiles.~~
- all wind (east, west, north, south) tiles have letters E, W, N or S on the corner of the tile.
- optionally, some versions have ~~honor~~ dragons (中, 发, 白) tiles labelled with letters C, F, B on the corner of the tile. Some other versions have the words RED, GREEN, WHITE on the top instead.
- Should there be bonus tiles (... flowers and seasons), there will be a number on the corner of the tiles to help differenciate the tiles.

**Comment by user670** [comment]
Acktchually with the new implementation that uses custom glyphs, ... ... numbers on dots and bamboos too please.

**Comment by C29H25N3O5** [comment]
I think that is not quite possible because Chinese and Japanese Mahjong tiles have different designs

**Comment by C29H25N3O5** [comment]
![image](https://user-images.githubusercontent.com/87485746/151608649-02a7e8ed-e82d-43ab-a76e-35a478af730a.jpeg)
This is a set of Chinese mahjong. Notice that they have three colours for the bamboo, characters, and circles. 

![image](https://user-images.githubusercontent.com/87485746/151608746-eb1cad18-5200-485f-99df-bce9a2617ca2.jpeg)

This is a set of Japanese mahjong.  The size is smaller and it only have two colours. Also the green dragon (發) is different than the Chinese one. The white dragon (白) has no frame. The orders of the dragon is "red, green, white", instead of "white, green, red" in the Chinese standard. The one of bamboo uses the peacock instead of the sparrow. 

![image](https://user-images.githubusercontent.com/87485746/151609242-2b8916dd-e941-42f8-a3d6-bb0e04bdf171.jpeg)

This is the European style mahjong. It has a joker tile which is similar to the function of the Joker in playing cards. 

![image](https://user-images.githubusercontent.com/87485746/151609343-bb9e06e5-1871-4e0f-a860-07f9f4ca2be0.jpeg)

American style. The three dragons uses the Initials of the Cantonese phonetic spellings.

**Comment by C29H25N3O5** [comment]
Also the in-game mahjong uses the Japanese rule (as in MahjongSoul, 雀魂), so the flower tiles are not used (But the red Doras (ドラ) are used).

**Comment by user670** [comment]
https://gamefaqs.gamespot.com/switch/286602-clubhouse-games-51-worldwide-classics/faqs/78437/riichi-mahjong

As shown in a screenshot from this page, the numbers and letters go on the Japanese set of tiles just fine. (Nintendo's Clubhouse Games on the Switch) I don't know what your concern is.

- If your concern is "this will involve making a new font, or code things that add the numbers/letters": yes, that *would* be unavoidable if we are to maje that.
- If your concern is "the numbers/letters aren't compatible with [insert whatever design]": heck it's just letters and numbers on the corners, how cone
- If your concern is "the numbers/letters aren't standardized": so is every other aspect of mahjong tile designs.
- If you instead argue "screw you, just remember the kanjis before you play": well you do you

**Comment by C29H25N3O5** [comment]
<img width="1246" alt="Screenshot 2022-01-28 at 13 41 19" src="https://user-images.githubusercontent.com/87485746/151611049-0a27ffed-c253-48b1-a45a-b0c4eb2c5786.png">
Actually, if you are using the latest snapshot version, the mahjong tiles are realised by those characters. I have made this compatible with both Chinese and Japanese designs but we would currently only use the Japanese one.

The real issue is that these frames are realised using combining characters with zero widths and negative x. It looks like this for now: 
<img width="1246" alt="Screenshot 2022-01-28 at 13 45 55" src="https://user-images.githubusercontent.com/87485746/151611665-2b8bfeae-b27a-41e0-b482-3eb62428a024.png">

The real issue is that there are not enough spaces for the letters and numbers. I cannot make the frame larger because that would exceed the em-square and all of the characters would squeeze together.

**Comment by user670** [comment]
Ok, that last argument is valid.

**Comment by C29H25N3O5** [comment]
But I think an alternative solution (although not elegant) would be to display the English names directly above the tile

**Comment by user670** [comment]
![Screenshot_20220129_035316_com adsk sketchbook](https://user-images.githubusercontent.com/22617255/151612576-bea35ca8-cf0e-4cb8-a1c9-9efb63ce9a92.jpg)

*highly* not elegant. Guess we can launch without that feature and see how many complaints from international players come in

**Comment by C29H25N3O5** [comment]
Actually, you can use the simplified Japanese Notations (Very common in MajSoul):
p = circle, m = character, s = bamboo;
ESWNWGR= 1~7z
So the image I sent above could be written as
1p9p1s9s1m9m1z2z3z4z5z6z7z

**Comment by user670** [comment]
but to be fair, even as someone who reads kanji, I still prefer the numbers, as that saves 0.5 seconds of me parsing the patterns on dot and bamboo tiles. I'm minorly pissed that the Chinese version of Mahjong Soul doesn't feature Int'l tiles.

**Comment by C29H25N3O5** [comment]
In fact the mobile version supports it (at least in iOS)

**Comment by user670** [comment]
putting "1m" above a tile only adds confusion ("what does the m mean?"), probably just add 1-9 above numbered tiles, and E/W/N/S above winds?

**Comment by C29H25N3O5** [comment]
The features mentioned above will be resolved in Techmino: Galaxy.

**Comment by C29H25N3O5** [comment]
![image](https://user-images.githubusercontent.com/87485746/168864150-4a008150-572b-42df-9c3b-e0dfc588f80a.jpeg)
There.
