### ISSUE TITLE
Zictionary: I did a thing that complicates things

### ISSUE THREAD

**Issue by user670** [26F-Studio/Techmino#868]
Some time earlier I made a, um, [this thing](https://github.com/user670/techmino-dictionary-converter). In short, I made a Python script that converts Markdown to Lua for Zictionary. However, this complicates quite a few things:

- The code I generated did not exactly match the format MrZ used to have, and as a result, it completely broke the [Online Dictionary](https://github.com/26F-Studio/techmino-online-dict).
- The tool is only useful if everyone starts editing the markdown instead of the Lua here. I don't think I need to explain why, and explaining why makes me sound like a childish idiot having some unrealistic day dream

So there is a decision that has to happen: either we as a group adopt my thing, or I bury by tool in the dirt and revert any damages done. Any thoughts?

早些时候我弄了个，呃，[东西](https://github.com/user670/techmino-dictionary-converter)。简而言之，我写了个能将markdown转换成小Z词典Lua的Python脚本。但是这东西搞砸了一些东西：

- 我生成的Lua代码和MrZ原有的代码格式不完全一样，因此完全搞坏了[在线词典](https://github.com/26F-Studio/techmino-online-dict)。
- 只有所有人都去编辑markdown而非在这编辑lua，工具才能实际有效。我觉得我不必解释原因，而且解释原因会让我看起来像个在做不现实的白日梦的幼稚的傻逼

所以现在需要做一个决策：要么所有人去用我的东西，要么我把我那个东西埋起来然后回退我造成的破坏。有想法吗？

**Comment by user670** [comment]
Working on a branch that reverts my damages. https://github.com/user670/Techmino/tree/user670-dict-damage-control

**Comment by ImpleLee** [comment]
For the first thing, that because some error in the online dictionary. Your tool is not what to blame.

For the second, I don't think adopting is better, considering what it will cost:
1. We need to maintain markdown instead of lua, so we have to generate the lua and make sure they align.
2. We need to change CI to generate the lua on the fly.
3. For local development, we have to always keep in mind that we have to run the tool before we can test locally.

All that said, how you generate the lua code is not what we want to restrict. As long as you can generate legal lua code, I don't think there is any issue. As for the online dictionary, not being able to parse a legal lua file is its own fault, not yours. So I don't think you have to revert your commit either.

**Comment by ImpleLee** [comment]
> > For the first thing, the trouble is due to error in the code for the online dictionary. Your tool is not what to blame.
> > For the second, I don't think adopting is better, considering what it will cost:
> > 
> > 1. We need to maintain markdown instead of lua, so we have to generate the lua and make sure they align.
> > 2. We need to change CI to generate the lua on the fly.
> > 3. For local development, we have to always keep in mind that we have to run the tool before we can test locally.
> > 
> > All that said, how you generate the lua code is not what we want to restrict. As long as you can generate legal lua code, I don't think there is any issue. As for the online dictionary, not being able to parse a legal lua file is its own fault, not yours. So I don't think you have to revert your commit either.
> 
> In other words,
> 
> * code that I already submitted can stay,
> * the use of the tool will not be supported by 26f studio
> 
> ?

Yes, that is what I mean.

**Comment by MrZ626** [comment]
\*You did a thing*

**Comment by user670** [comment]
> *You did a thing*

A thing that turns out to be, uh, pretty pointless

**Comment by RubixYouTube** [comment]
`Black Hole`
